@startuml Exemple1
 


actor "Пользователь" as user
participant "компьютер Пользователя" as comp
participant "сервер СВФУ\n(www.s-vfu.ru)" as server


user++
user -[#green]> comp: 1. Вход в систему
    comp++
    autonumber 1.1
        comp -[#blue]> server: GET /user/rasp/new/
        server++
            server -[#red]-> comp: Response: отклик с html-кодом
        server--        
        comp -[#DarkCyan]-> user: главная страница 
        note left
            пользователь попадает
            на главную страницу 
            системы публикации
            расписания
        end note
    autonumber stop

user -[#green]> comp: 2. Выбор группы и плана
    autonumber 2.1
        comp -[#blue]> server: POST /user/rasp/new/ajax.php, action: loadgroup
        server++
            server -[#red]-> comp: Response: отклик с html-кодом
        server--
        comp -[#DarkCyan]-> user: список групп и планов 
        note left
            пользователь получает
            список групп и планов
        end note
    autonumber stop
    

user -[#green]> comp: 3.1 Выбор РУПа
    autonumber 3.1.1
        comp -[#blue]> server: POST /user/rasp/new/ajax.php, action: choicerup
        server++
            server -[#red]-> comp: Response: отклик с html-кодом
            comp -[#DarkCyan]-> user: форма с подтверждением
            note left
                пользователь получает
                форму с выбором РУПа
            end note
            autonumber stop
            user -[#green]> comp: 3.2 Выбор РУПа
            autonumber 3.2.1
            comp -[#blue]> server: POST /user/rasp/new/, action: show
            server -[#red]-> comp: Response: отклик с html-кодом
        server--
        comp -[#DarkCyan]-> user: расписание группы
        note left
            пользователь получает
            таблицу с расписанием
            занятий группы 
            (может быть пустой)
        end note
    autonumber stop


user -[#green]> comp: 4.1 Добавление строки с занятием
    autonumber 4.1.1

        comp -[#blue]> server: POST /user/rasp/new/ajax.php, action: addrow
        server++
            server -[#red]-> comp: Response: отклик с html-кодом
        server--
        comp -[#DarkCyan]-> user: форма для заполнения
        note left
            пользователь получает
            форму с полями для
            заполнения данных
        end note
        autonumber stop
user -[#green]> comp: 4.2 Отправка заполненной формы
        autonumber 4.2.1
        comp -[#blue]> server: POST /user/rasp/new/, action: insertrow
        server++
            server -[#red]-> comp: Response: отклик с html-кодом
        server--
        comp -[#DarkCyan]-> user: расписание группы
        note left
            пользователь получает
            обновленную таблицу 
            с расписанием группы
        end note
    autonumber stop

user -[#green]> comp: 5.1 Публикация расписания
    autonumber 5.1.1

        comp -[#blue]> server: POST /user/rasp/new/ajax.php, action: public
        server++
            server -[#red]-> comp: Response: отклик с html-кодом
        server--
            comp -[#DarkCyan]-> user: форма подтвержления публикации
        note left
            пользователь получает
            форму подтверждения
            публикации расписания
        end note

        autonumber stop
        user -[#green]> comp: 5.2 Подтверждение публикации
        autonumber 5.2.1
        
        comp -[#blue]> server: POST /user/rasp/new/, action: public    
        server++
        server -[#red]-> comp: Response: отклик с html-кодом        
        server--
        comp -[#DarkCyan]-> user: сообщение об успехе
        note left
            пользователь получает
            уведомление о успешной 
            публикации расписания
        end note
      comp--  
    autonumber stop 
 
@enduml